### ISSUE TITLE
How to Install it?

### ISSUE THREAD

**Issue by MSGitt** [TorchMoE/MoE-Infinity#10]
When I install through git clone https://github.com/TorchMoE/MoE-Infinity.git, 
there are only CITATIONS.md, LICENSE, and README.md files in the directory. 

Therefore, it is impossible to install through pip install -e . and I do not know how to use it. 
Should I use it via the dev branch?

Thank you.

**Comment by drunkcoding** [comment]
It is now released to main

**Comment by MSGitt** [comment]
I checked, thank you so much!
