### ISSUE TITLE
Install from pip failed

### ISSUE THREAD

**Issue by future-xy** [TorchMoE/MoE-Infinity#11]
Tried to install following README:
```
pip install moe-infinity
conda install -c conda-forge libstdcxx-ng=12 # assume using conda, otherwise install libstdcxx-ng=12 using your package manager or gcc=12
```
But got,
```
$ pip install moe-infinity
ERROR: Could not find a version that satisfies the requirement moe-infinity (from versions: none)
ERROR: No matching distribution found for moe-infinity
```

Is it because the lib is not released on `pip` yet?

**Comment by drunkcoding** [comment]
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ moe-infinity

**Comment by future-xy** [comment]
This works but we need to either add this to readme or update pip release.

> pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ moe-infinity
